/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;

import javax.swing.SwingUtilities;

public class Main {
   
    public static void main(String[] args) {
       SwingUtilities.invokeLater(() -> new Counter().setVisible(true));
    }
}
